export interface Filters {
	intelligence: boolean;
	strength: boolean;
	dexterity: boolean;
	// physical: boolean;
	// chaos: boolean;
	// fire: boolean;
	// cold: boolean;
	// lightning: boolean;
	// spell: boolean;
	// attack: boolean;
	// area: boolean;
	// aura: boolean;
	// chaining: boolean;
	// channelling: boolean;
	// critical: boolean;
	// curse: boolean;
	// duration: boolean;
	// guard: boolean;
	// hex: boolean;
	// mark: boolean;
	// melee: boolean;
	// mine: boolean;
	// minion: boolean;
	// movement: boolean;
	// nova: boolean;
	// projectile: boolean;
	// slam: boolean;
	// stance: boolean;
	// strike: boolean;
	// totem: boolean;
	// trap: boolean;
	// trigger: boolean;
	// vaal: boolean;
	// awakened: boolean;
	// exceptional: boolean;
	// grants_active_skill: boolean;
	// support: boolean;
}
